// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppRouter: typeof import('./src/layouts/AppRouter.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    DefaultLayout: typeof import('./src/layouts/DefaultLayout.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeLayout: typeof import('./src/layouts/HomeLayout.vue')['default']
    IBiSkipEndFill: typeof import('~icons/bi/skip-end-fill')['default']
    IBiSkipStartFill: typeof import('~icons/bi/skip-start-fill')['default']
    ICarbonChevronLeft: typeof import('~icons/carbon/chevron-left')['default']
    ICarbonChevronRight: typeof import('~icons/carbon/chevron-right')['default']
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonPauseFilled: typeof import('~icons/carbon/pause-filled')['default']
    ICarbonPlayFilledAlt: typeof import('~icons/carbon/play-filled-alt')['default']
    ICarbonSearch: typeof import('~icons/carbon/search')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
    ICarbonVolumeMute: typeof import('~icons/carbon/volume-mute')['default']
    ICarbonVolumeUp: typeof import('~icons/carbon/volume-up')['default']
    ICodiconChromeClose: typeof import('~icons/codicon/chrome-close')['default']
    ICodiconChromeMaximize: typeof import('~icons/codicon/chrome-maximize')['default']
    ICodiconChromeMinimize: typeof import('~icons/codicon/chrome-minimize')['default']
    IPhPlaylist: typeof import('~icons/ph/playlist')['default']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NCard: typeof import('naive-ui')['NCard']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCarouselItem: typeof import('naive-ui')['NCarouselItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NEl: typeof import('naive-ui')['NEl']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpin: typeof import('naive-ui')['NSpin']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideScrubber: typeof import('./src/components/SlideScrubber.vue')['default']
  }
}

export {}
